### ISSUE TITLE
Checklist before release

### ISSUE THREAD

**Issue by michael-weigelt** [dfinity/wasmtime-hs#41]
- [x] Linker support
	- https://github.com/dfinity/wasmtime-hs/pull/40
- [x] Use unsafe C calls where possible
	- Sheng has a list in his repo
- [x] Finalize callbacks
	- https://github.com/dfinity/wasmtime-hs/blob/master/lib/Wasmtime.hs#L1391C5-L1391C20
	- Callback ptrs: Have a list (IORef) in Store record and finalize list of ptrs when we finalize the Store
- [ ] Check if C API is completely covered? 
- [ ] Documentation: 
	- [ ] Complete
	- [ ] Order like rust doc
- [ ] Have example at top of haddock
- [x] Rename to wasmtime-hs
